# yaml-language-server: $schema=https://deltares.github.io/veriflow/v0/config.schema.json
version: v0
general:
  verification_period:
    dimension: forecast_reference_time
    start: "2026-05-15T00:00:00Z"
    end: "2026-05-20T00:00:00Z"
  verification_pairs:
    - variable: PC_IFS
      id: PC_IFS
      obs: observed
      sim: simulated_IFS

      # Add GEFS and GEPS 
  lead_times:
    unit: D
    values: [1, 2, 3, 4, 5]
datasources:
  - import_adapter: fewswebservice
    source: observed
    data_type: observed_historical
    location_ids: ["3031092"]
    parameter_ids: ["PC.obs"]
    module_instance_id: ImportMeteoStations
    webservice_version: "2025.02"
  - import_adapter: fewswebservice
    source: simulated_IFS
    data_type: simulated_forecast_ensemble
    location_ids: ["3031092"]
    parameter_ids: ["PC.nwp"]
    module_instance_id: PreprocessIFS
    webservice_version: "2025.02"
scores:
  - score_adapter: crps_for_ensemble
    scores: []
    reduce_dims: []
datasinks:
  - export_adapter: cf_compliant_netcdf
    directory: .
    filename: IFS_precip_Elbow.nc
    institution: OpenFEWS
    title: IFS precipitation verification
    force_overwrite: true
id_mapping:
  station:
    "3031092":
      observed: "3031092"
      simulated_IFS: "3031092"
  variable:
    PC_IFS:
      observed: PC_obs
      simulated_IFS: PC_nwp
