# yaml-language-server: $schema=https://deltares.github.io/veriflow/v0/config.schema.json
version: v0
general:
  verification_period:
    dimension: time
    start: "2026-05-15T00:00:00Z"
    end: "2026-06-01T00:00:00Z"
  verification_pairs:
    - variable: PC
      id: PC
      obs: observed
      sim: simulated
  lead_times:
    unit: D
    values: [1, 2, 3, 4, 5, 6, 7]
datasources:
  - import_adapter: fewswebservice
    source: observed
    data_type: observed_historical
    location_ids: ["3031092"]
    parameter_ids: ["PC.obs"]
    module_instance_id: ImportMeteoStations
    webservice_version: "2025.02"
  
  - import_adapter: fewswebservice
    source: simulated
    data_type: simulated_forecast_single
    location_ids: ["3031092"]
    parameter_ids: ["PC.nwp"]
    module_instance_id: PreprocessGDPS
    webservice_version: "2025.02"
scores:
  - score_adapter: continuous_scores
    scores: [mean_error, mae, rmse]
    reduce_dims: []
datasinks:
  - export_adapter: cf_compliant_netcdf
    directory: .
    filename: GDPS_precip_Elbow.nc
    institution: OpenFEWS
    title: GDPS precipitation verification
    force_overwrite: true

id_mapping:
  station:
    "3031092":
      observed: "3031092"
      simulated: "3031092"
  variable:
    PC:
      observed: PC_obs
      simulated: PC_nwp
